name: 'Community operators action'
description: 'Community operator action for operator testing'
inputs:
  stream:
    description: 'Operator stream name (community-operators or upstream-community-operators)'
    required: true
    default: 'community-operators'
  name:
    description: 'Operator name'
    # required: true
    default: 'aqua'
  version:
    description: 'Operator version'
    # required: true
    default: '5.3.0'
  operator-dir:
    description: 'Path to operator (community-operators/aqua or local/path/to/operator). If empty <stream>/<name> will be used'
    # required: true
    default: ''
runs:
  using: "composite"
  steps:
    # - name: Checkout community operators repo
    #   uses: actions/checkout@v2
    #   with:
    #     repository: operator-framework/community-operators
    #     ref: master
    - id: operator-test
      name: "Operator test"
      env:
        OPA_STREAM: "${{ inputs.stream }}"
        OPA_NAME: "${{ inputs.name }}"
        OPA_VERSION: "${{ inputs.version }}"
        OPA_OPERATOR_DIR: "${{ inputs.operator-dir }}"
      run: ${{ github.action_path }}/action.sh
      shell: bash
