name: 'Community operators action'
description: 'Community operator action for operator testing'
inputs:
  test-type:
    description: 'Test type (kiwi,lemon or orange)'
    required: true
    default: 'kiwi'
  stream:
    description: 'Operator stream name (community-operators or upstream-community-operators)'
    required: true
    default: 'community-operators'
  name:
    description: 'Operator name'
    # required: true
    default: 'aqua'
  version:
    description: 'Operator version'
    # required: true
    default: '5.3.0'
  repo:
    description: 'Community operators repo'
    default: 'https://github.com/operator-framework/community-operators.git'
  branch:
    description: 'Community operators branch'
    default: 'master'
  repo-dir:
    description: 'Repo directory when if not community-operators'
    default: 'community-operators'
  operator-dir:
    description: 'Path to operator (community-operators/aqua or local/path/to/operator). If empty <stream>/<name> will be used'
    default: ''
  pr-labels:
    description: 'Space separated list of labels in PR'
    default: ''
runs:
  using: "composite"
  steps:
    - id: operator-test
      name: "Operator test"
      env:
        OPA_TEST_TYPE: "${{ inputs.test-type }}"
        OPA_STREAM: "${{ inputs.stream }}"
        OPA_NAME: "${{ inputs.name }}"
        OPA_VERSION: "${{ inputs.version }}"
        OPA_REPO: "${{ inputs.repo }}"
        OPA_BRANCH: "${{ inputs.branch }}"
        OPA_REPO_DIR: "${{ inputs.repo-dir }}"
        OPA_OPERATOR_DIR: "${{ inputs.operator-dir }}"
        OPA_PR_LABELS: "${{ inputs.pr-labels }}"
      run: ${{ github.action_path }}/action.sh
      shell: bash
